<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClaudeBridge.Core\ClaudeBridge.Core.csproj" />
    <ProjectReference Include="..\ClaudeBridge.GeometryEngine\ClaudeBridge.GeometryEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
